'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  analyse-logs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3
      - name: Clone and shift tests
        run: cd src/workflow_utils
      - name: check_val
        run: ls src/ && ls ../
      - uses: actions/upload-artifact@v3
        with:
          name: sample log file upload as artifact
          path: ./src/sample_log.log
      - uses: PlayWithGithubActions/log-ai-analysis@v2.0.0
        name: Error Log Analysis
        with:
          api-key: ${{ secrets.API_KEY }}
          file_path: ./src/sample_log.log
          output-file: report
      - name: Send notification email
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: python ./src/workflow_utils/send_mail.py
      